cfd/urls.py
"""
crudapp URL Configuration
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
"""
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin
from cfd import views

#added for form preview
from django import forms

from cfd.forms import CFDForm
from cfd.forms import CFDFormPreview

app_name = 'cfd'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.cfd_list, name='cfd_list'),
    url(r'^list$', views.cfd_list, name='cfd_list'),
    url(r'^templates$', views.template_list, name='template_list'),
    url(r'^new$', views.cfd_create, name='cfd_new'),
    url(r'^new_multi$', views.cfd_create_mutiple, name='cfd_new_multi'),
    url(r'^edit/(?P<pk>\d+)$', views.cfd_update, name='cfd_edit'),
    url(r'^copy/(?P<pk>\d+)$', views.cfd_copy, name='cfd_copy'),
    url(r'^history/(?P<pk>\d+)$', views.cfd_history, name='cfd_history'),
    url(r'^history/(?P<pk>\d+)/(?P<detail_pk>\d+)$', views.cfd_history_detail, name='cfd_history_detail'),
    url(r'^delete/(?P<pk>\d+)$', views.cfd_delete, name='cfd_delete'),
    url(r'^post/$', CFDFormPreview(CFDForm)),
    path('accounts/', include('django.contrib.auth.urls')),

]

remedy/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from cfd import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cfd/', include('cfd.urls')),
    path('', views.cfd_list, name='cfd_list'),
]

cfd/models.py
import logging
import calendar
from datetime import *
from dateutil.relativedelta import *

from django.db import models
from django.contrib.auth import get_user_model

import reversion

from cfd.fields import MultiSelectField
from cfd.managers import HistoryManager

User = get_user_model()

# Create your models here.

# This is a placeholder model. This should be replaced with a reference to the client table in the production database.
# You can either update this model with all the fields in the client table, or cerate a view with just the Client Name and just adjust the class name to match the name of the table.
# If you do change the class name, you must also change it in the CFD Model below where the forign key constraint is defined
class client(models.Model):
    #define fields
    #format is [database_column_name] = models.[FiedlType]('[Display Name]',[options])
    CLIENT_NAME	= models.CharField('Client Name',max_length=255)

    def __str__(self):
        return self.CLIENT_NAME

@reversion.register()
class cfd(models.Model):
    class Meta:
            verbose_name = 'Client Financial Record'
            verbose_name_plural = 'Client Financial Records'


# define drop down values
# An iterable (e.g., a list or tuple) consisting itself of iterables of exactly two items (e.g. [(A, B), (A, B) ...]) to use as choices for this field. If choices are given, they’re enforced by model validation and the default form widget will be a select box with these choices instead of the standard text field.
# The first element in each tuple is the actual value to be set on the model, and the second element is the human-readable name.
# FYI, the number in the object names refers to the table ID in the excel spreadsheet I was given.
# In a future version, you migth wnat to create lookup tables in the database for each drop down. You could then update the drop down options without changing code. In this case, the dropdown fields should be replaced with forign keys

    DROP_DOWN_MENU_21_CHOICES = (
        ('Y','Y'),
        ('N','N'),
        ('TBD','TBD')
    )
    
    DROP_DOWN_MENU_23_CHOICES = (
        ('Y - Retail-90','Y - Retail-90'),
        ('Y - Retail at Mail Rates','Y - Retail at Mail Rates'),
        ('Y - Retail-90 & Retail at Mail Rates','Y - Retail-90 & Retail at Mail Rates'),
        ('N','N')
    )

    DROP_DOWN_MENU_24_CHOICES = (
        ('Include - Explicit in Contract','Include - Explicit in Contract'),
        ('Include - Assumed by CE','Include - Assumed by CE'),
        ('Exclude - Explicit in Contract','Exclude - Explicit in Contract'),
        ('Exclude - Assumed by CE','Exclude - Assumed by CE'),
        ('TBD','TBD')
    )

    DROP_DOWN_MENU_25_CHOICES = (
        ('Include in GER - Explicit in Contract','Include in GER - Explicit in Contract'),
        ('Include in GER - Assumed by CE','Include in GER - Assumed by CE'),
        ('Include in BER - Explicit in Contract','Include in BER - Explicit in Contract'),
        ('Include in BER - Assumed by CE','Include in BER - Assumed by CE'),
        ('Exclude - Explicit in Contract','Exclude - Explicit in Contract'),
        ('Exclude - Assumed by CE','Exclude - Assumed by CE'),
        ('TBD','TBD')
    )
    
    DROP_DOWN_MENU_41 = (
        ('Transplant','Transplant'),
        ('Hepatitis B','Hepatitis B'),
        ('CMV Agents','CMV Agents'),
        ('HIV','HIV'),
        ('Anticoagulants','Anticoagulants'),
        ('Hepatitis C','Hepatitis C'),
        ('PCSK9','PCSK9'),
        ('TBD','TBD')
        )
    
    DROP_DOWN_MENU_CONTRACT_TYPE_CHOICES = (
        ('Baseline Remedy','Baseline Remedy'),
        ('Previous PBM Contract','Previous PBM Contract'),
        ('Standard','Standard'),
        ('TBD','TBD')
    )
    
    DROP_DOWN_MENU_42 = (
        ('Per Brand','Per Brand'),
        ('Per Rx','Per Rx'),
        ('TBD','TBD')
    )
    
    default_contract_start_date = date.today()
    default_contract_end_date = default_contract_start_date+relativedelta(years=+1)
    
    #define fields
    #format is [database_column_name] = models.[FiedlType]('[Display Name]',[options])
    #If the name of the client model is changed, you must also change it here
    CLIENT = models.ForeignKey(
                                client,
                                on_delete=models.PROTECT)
    CONTRACT_DESCRIPTION = models.TextField('Contract Description',max_length=500,blank=True)
    CONTRACT_TYPE = models.CharField('Contract Type',max_length=25,choices=DROP_DOWN_MENU_CONTRACT_TYPE_CHOICES)
    START_DATE = models.DateField('Contract Start Date',default=default_contract_start_date)
    END_DATE = models.DateField('Contract End Date',default=default_contract_end_date)
    GUAR_BM_EZBD_DCT = models.DecimalField('Mail Brand AWP Discount (excluding ZBDs)',max_digits=6, decimal_places=3, default=0)
    #GUAR_BM_EZBD_DCT = models.PercentField('Mail Brand AWP Discount (excluding ZBDs)')
    GUAR_BM_IZBD_DCT = models.DecimalField('Mail Brand AWP Discount (including ZBDs)',max_digits=6, decimal_places=3, default=0)
    GUAR_BR_EZBD_DCT = models.DecimalField('Retail Brand AWP Discount (excluding ZBDs)',max_digits=6, decimal_places=3, default=0)
    GUAR_BR_IZBD_DCT = models.DecimalField('Retail Brand AWP Discount (including ZBDs)',max_digits=6, decimal_places=3, default=0)
    GUAR_GM_EZBD_DCT = models.DecimalField('Mail Generic AWP Discount (excluding ZBDs)',max_digits=6, decimal_places=3, default=0)
    GUAR_GM_IZBD_DCT = models.DecimalField('Mail Generic AWP Discount (including ZBDs)',max_digits=6, decimal_places=3, default=0)
    GUAR_GR_EZBD_DCT = models.DecimalField('Retail Generic AWP Discount (excluding ZBDs)',max_digits=6, decimal_places=3, default=0)
    GUAR_GR_IZBD_DCT = models.DecimalField('Retail Generic AWP Discount (including ZBDs)',max_digits=6, decimal_places=3, default=0)
    GUAR_MAIL_REBATE = models.CharField('Guarantee Mail Rebate',max_length=15,choices=DROP_DOWN_MENU_42,default="TBD")
    GUAR_R90_REBATE = models.CharField('Guarantee Retail 90 Rebate',max_length=15,choices=DROP_DOWN_MENU_42,default="TBD")
    GUAR_RETAIL_REBATE = models.CharField('Guarantee Retail Rebate',max_length=15,choices=DROP_DOWN_MENU_42,default="TBD")
    GUAR_SPC_BR_DCT = models.DecimalField('Specialty Brand AWP Discount - Retail',max_digits=6, decimal_places=3, default=0)
    GUAR_SPC_GR_DCT = models.DecimalField('Specialty Generic AWP Discount - Retail',max_digits=6, decimal_places=3, default=0)
    GUAR_SPC_M_REBATE = models.CharField('Guarantee Specialty Mail Rebate',max_length=15,choices=DROP_DOWN_MENU_42,default="TBD")
    GUAR_SPC_R_REBATE = models.CharField('Guarantee Specialty Retail Rebate',max_length=15,choices=DROP_DOWN_MENU_42,default="TBD")
    GUAR_SPC_SRX_B_DCT = models.DecimalField('Specialty Brand AWP Discount - SRx',max_digits=6, decimal_places=3, default=0)
    GUAR_SPC_SRX_G_DCT = models.DecimalField('Specialty Generic AWP Discount - SRx',max_digits=6, decimal_places=3, default=0)
    #RETAIL_90_MAIL_RATES = models.CharField('Retail-90/Retail at Mail Rates',max_length=50,choices=DROP_DOWN_MENU_23_CHOICES)
    RETAIL_90_MAIL_RATES_B = models.CharField('Brand Retail-90/Retail at Mail Rates', max_length=50, choices=DROP_DOWN_MENU_23_CHOICES)
    #IF RETAIL_90_MAIL_RATES_B = 'N' THEN GUAR_BR90_EZBD_DCT, GUAR_BR90_IZBD_DCT, GUAR_BR90_DISP_FEE, RETAIL_90_MAIL_RATES_B_DS disappear
    GUAR_BR90_EZBD_DCT = models.DecimalField('Retail-90 Brand AWP Discount (excluding ZBDs)', max_digits=6,decimal_places=3, default=0)
    GUAR_BR90_IZBD_DCT = models.DecimalField('Retail-90 Brand AWP Discount (including ZBDs)', max_digits=6,decimal_places=3, default=0)
    GUAR_BR90_DISP_FEE = models.DecimalField('Retail-90 Brand Dispensing Fee',max_digits=6, decimal_places=3, default=0)
    RETAIL_90_MAIL_RATES_B_DS = models.IntegerField('Retail-90/Retail at Mail Rates Brand Days Supply Breakout',default=0)
    #end RETAIL_90_MAIL_RATES_B dependnet fields
    RETAIL_90_MAIL_RATES_G = models.CharField('Generic Retail-90/Retail at Mail Rates', max_length=50, choices=DROP_DOWN_MENU_23_CHOICES)
    # IF RETAIL_90_MAIL_RATES_G = 'N' THEN GUAR_GR90_EZBD_DCT, GUAR_GR90_IZBD_DCT, GUAR_GR90_DISP_FEE, RETAIL_90_MAIL_RATES_G_DS disappear
    GUAR_GR90_EZBD_DCT = models.DecimalField('Retail-90 Generic AWP Discount (excluding ZBDs)', max_digits=6,decimal_places=3, default=0)
    GUAR_GR90_IZBD_DCT = models.DecimalField('Retail-90 Generic AWP Discount (including ZBDs)', max_digits=6,decimal_places=3, default=0)
    GUAR_GR90_DISP_FEE = models.DecimalField('Retail-90 Generic Dispensing Fee',max_digits=6, decimal_places=3, default=0)
    RETAIL_90_MAIL_RATES_G_DS = models.IntegerField('Retail-90/Retail at Mail Rates Generic Days Supply Breakout',default=0)
    #end RETAIL_90_MAIL_RATES_G dependnet fields
    RETAIL_REBATE_TYPE = models.CharField('Retail Rebate Type',max_length=15,choices=DROP_DOWN_MENU_42,default="TBD")
    RETAIL_SPC_REBATE_TYPE = models.CharField('Retail Specialty Rebate Type',max_length=15,choices=DROP_DOWN_MENU_42,default="TBD")
    GUAR_BM_DISP_FEE = models.DecimalField('Mail Brand Dispensing Fee',max_digits=6, decimal_places=3, default=0)
    GUAR_BR_DISP_FEE = models.DecimalField('Retail Brand Dispensing Fee',max_digits=6, decimal_places=3, default=0)
    GUAR_GM_DISP_FEE = models.DecimalField('Mail Generic Dispensing Fee',max_digits=6, decimal_places=3, default=0)
    GUAR_GR_DISP_FEE = models.DecimalField('Retail Generic Dispensing Fee',max_digits=6, decimal_places=3, default=0)
    GUAR_SPC_B_SRX_DISP_FEE = models.DecimalField('Specialty Brand Dispensing Fee - SRx',max_digits=6, decimal_places=3, default=0)
    GUAR_SPC_BR_DISP_FEE = models.DecimalField('Specialty Brand Dispensing Fee - Retail',max_digits=6, decimal_places=3, default=0)
    GUAR_SPC_G_SRX_DISP_FEE = models.DecimalField('Specialty Generic Dispensing Fee - SRx',max_digits=6, decimal_places=3, default=0)

cfd/templates/base.html
<!--This file contains the HTML code for the page headers and footers. Other templates will insert thier content in the "block main" section.-->
<!doctype html>
<html lang="en">
<head>
    <title>Remedy Client Financial Database</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/dashboard.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous" />
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
    <link rel="stylesheet" type="text/css" href="/static/style.css">

    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">


</head>
<body>
<!-- Header -->
<div id="header">
    <div id="branding">
        <h1 id="site-name"><a href="/cfd/">Remedy Client Financial Database</a></h1>
    </div>
    <div id="user-tools">
        Welcome, <strong>dan</strong>.
        <a href="/cfd/">Home</a> /
        <a href="/admin/">Admin Site</a>
        <a href="/admin/password_change/">Change password</a> /
        <a href="/admin/logout/">Log out</a>
    </div>
</div>
<!-- END Header -->
<hr>
{% block main %}
{% endblock %}
</body>

<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js" integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E=" crossorigin="anonymous"></script>

{% block scripts %}
{% endblock %}
</html>

cfd/templates/cfd_confirmation.html
<!--Template for the save confirmation screen-->
<!-- This line specifies that the content here should be merged into the base.html-->
{% extends 'base.html' %}
{% load i18n static %}
{% load filters %}
{% load static %}

{% block main %}
     <form  method="post" id="cfd_form">{% csrf_token %}
         <input type="hidden" name="is_confirmation_page" value="True"/>
         <div class="row">
            {% if formset %}
                {{ formset.management_form }}
               <div class="col">
                     {% include "snippets/formset.html" with formset=formset changed=changed confirmation=True fieldsets=fieldsets R90_B_LIST=RETAIL_90_MAIL_RATES_B_LIST R90_G_LIST=RETAIL_90_MAIL_RATES_G_LIST %}
               </div>
            {% else %}
                <div class="col">
                    {% include "snippets/form_snippet.html" with form=form fieldsets=fieldsets changes=changed confirmation=True index=0 last=True %}
                </div>
            {% endif %}           
         </div>

         
            
       <input class="btn btn-primary" type="submit" value="Confirm Changes" />
    </form>

 {% endblock %}

{% block scripts %}

<script src="{% static '/admin/js/vendor/jquery/jquery.js' %}"></script>
<script src="{% static '/admin/js/jquery.init.js' %}"></script>
<script src="{% static '/admin/js/core.js' %}"></script>
<script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
<script src="{% static '/js/collapse.js' %}"></script>

{% endblock %}

cfd/templates/cfd_delete.html
<!--Template for the delete confirmation screen-->
<!-- This line specifies that the content here should be merged into the base.html-->
{% extends 'base.html' %}

{% block main %}
    <div class="container">
      <form method="post">{% csrf_token %}
        Are you sure you want to delete "{{ object }}" ?
        <input class="btn btn-primary" type="submit" value="Yes" />
      </form>
    </div>
{% endblock %}

cfd/templates/cfd_form.html
<!--Template for the standard update screen-->
<!-- This line specifies that the content here should be merged into the base.html-->
{% extends 'base.html' %}
{% load i18n static %}
{% load filters %}
{% load static %}

{% block main %}
    <!--begin Search Form-->
    <div id="field-search-container">
        <label id="field-search-label"> Search Fields </label>
        <input id="field-search" type="text"/>
    </div>
    <!--End Search Form-->

    <form  method="post" id="cfd_form">{% csrf_token %}
         <div class="row">
            {% if formset %}
                {{ formset.management_form }}
                <div class="col">
                    {% include "snippets/formset.html" with formset=formset fieldsets=fieldsets R90_B_LIST=RETAIL_90_MAIL_RATES_B_LIST R90_G_LIST=RETAIL_90_MAIL_RATES_G_LIST %}
                </div>
            {% else %}
                <div class="col">
                    {% include "snippets/form_snippet.html" with form=form fieldsets=fieldsets %}
                </div>
            {% endif %}           
         </div>

        {% if create %}
            <input id="submit" class="btn btn-primary" type="submit" value="Save as Pending" />

            <button type="button" class="btn btn-primary cfd-btn" data-toggle="modal" data-target="#myModal">
                Save and Submit
            </button>
                
            <div class="modal" id="myModal">
                <div class="modal-dialog">
                    <div class="modal-content">
                            
                    <div class="modal-header">
                        <h4 class="modal-title">Confirm Form Submission</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                
                    <div class="modal-body">
                        Confirm your changes and submit.
                    </div>
                
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                        <input id="submit" class="btn btn-primary" type="submit" value="Save" />
                    </div>
                
                    </div>
                </div>
            </div>
        {% else %}
            <input id="submit-pending" class="btn btn-primary" type="submit" value="Save as Pending" />

            <input id="submit" class="btn btn-primary" type="submit" value="Save and Submit" />
       {% endif %}
    </form>

 {% endblock %}

{% block scripts %}

<script src="{% static '/admin/js/vendor/jquery/jquery.js' %}"></script>
<script src="{% static '/admin/js/jquery.init.js' %}"></script>
<script src="{% static '/admin/js/core.js' %}"></script>
<script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
<script src="{% static '/js/collapse.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="{% static '/js/forms.js' %}"></script>

{% endblock %}

cfd/templates/cfd_history.html
<!--Template for the history view screen-->
<!-- This line specifies that the content here should be merged into the base.html-->
{% extends 'base.html' %}

{% block main %}
    <table class="cfd-list">
        <thead>
            <th>Date/Time</th>
            <th>Done By</th>
            <th>Changes</th>
            <th></th>
        </thead>       
        <tbody>
            {% for log in logs %}
            <tr>
                <td>{{ log.revision.date_created }}</td>
                <td>{{ log.revision.user }}</td>
                <td>{{ log.revision.comment|linebreaks }}</td>
                <td>
                    <a href="{% url "cfd:cfd_history_detail" record.id log.id %}">Details</a>
                </td>
            </tr>
            {% endfor %}
        </tbody> 
    </table>
{% endblock %}

cfd/templates/cfd_list.html
<!--Template for the home screen listing records-->
<!-- This line specifies that the content here should be merged into the base.html-->
{% extends 'base.html' %}

{% block main %}
    <div class="container">
        <h1>Client Financial Data</h1>
        <div class="search-bar">
          <form method="POST"> {% csrf_token %}
            <!-- {{ form }} -->
            <div class="row">
              {% for field in form %}
                <div class="col search-field-col">
                  {{ field }}
                </div>
              {% endfor %}
              <div class="col search-field-col">
                <input class="search-btn" type="submit" value="Search" />
              </div>              
            </div>  
            {{ form.errors }}          
          </form>
        </div>        
        
        <div id="new-button-container">
          <a href="{% url "cfd:cfd_new" %}">
            <button class="btn btn-primary cfd-btn new-form-btn">
                <span class="oi oi-plus"></span> New Client Financial Data entry
            </button>
          </a>
          <a href="{% url "cfd:template_list" %}">
            <button class="btn btn-primary cfd-btn new-form-btn">
                <span class="oi oi-plus"></span> New Client Financial Data entry from template
            </button>
          </a>
        </div>

        <div class="cfd-section">
          <h2>Client Data</h2>
          <table class="cfd-list">
            {% for r in object_list %}
            <tr><td><a href="{% url "cfd:cfd_edit" r.id %}">{{ r.CLIENT }}: {{ r.START_DATE }} - {{ r.END_DATE }}</a></td>
            <td><a href="{% url "cfd:cfd_history" r.id %}">History</a></td>
            <td><a href="{% url "cfd:cfd_copy" r.id %}">Copy</a></td>
            <td><a href="{% url "cfd:cfd_delete" r.id %}">Delete</a></td>
            </tr>
            {% endfor %}
          </table>
        </div>

        <div class="cfd-section">
          <h2>Pending Review</h2>
          <table class="cfd-list">
            {% for r in pending %}
            <tr><td><a href="{% url "cfd:cfd_edit" r.id %}">{{ r.CLIENT }}: {{ r.START_DATE }} - {{ r.END_DATE }}</a></td>
            <td><a href="{% url "cfd:cfd_history" r.id %}">History</a></td>
            <td><a href="{% url "cfd:cfd_copy" r.id %}">Copy</a></td>
            <td><a href="{% url "cfd:cfd_delete" r.id %}">Delete</a></td>
            </tr>
            {% endfor %}
          </table>
        </div>

        <div class="cfd-section">
          <h2>Templates</h2>
          <table class="cfd-list">
            {% for r in templates %}
            <tr><td width=255><a href="{% url "cfd:cfd_edit" r.id %}">{{ r.CONTRACT_DESCRIPTION }}</a></td>
            <td><a href="{% url "cfd:cfd_copy" r.id %}">Create New From Template</a></td>
            <td><a href="{% url "cfd:cfd_delete" r.id %}">Delete</a></td>
            </tr>
            {% endfor %}
          </table>
        </div>


    </div>
{% endblock %}

{% block scripts %}
    <script>
      $( function() {
        $( "#id_start_date" ).datepicker();
        $( "#id_end_date" ).datepicker();
      } );
    </script>
{% endblock %}

cfd/templates/cfd_new_multi.html
<!--Template for the create new record screen-->
<!-- This line specifies that the content here should be merged into the base.html-->
{% extends 'base.html' %}
<script>

</script>
{% block main %}
    <div class="errorlist">
        {{ form.non_field_errors }}
        {{ form.name_of_field.errors }}
    </div>
     <form  method="post" id="cfd_form">{% csrf_token %}
         <table><tr>
             {% for form in formset %}
                <td>
                <table>
                {% if forloop.first %}
                    {% for field in form %}
                        {% if field.name in RETAIL_90_MAIL_RATES_B_LIST %}
                            <tr class="RETAIL_90_MAIL_RATES_B_FIELD fieldWrapper">
                        {% elif field.name in RETAIL_90_MAIL_RATES_G_LIST %}
                            <tr class="RETAIL_90_MAIL_RATES_G_FIELD fieldWrapper">
                        {% else %}
                            <tr class="fieldWrapper"> <!-- no match in loop, normal row -->
                        {% endif %}
                        <td>{{ field.label_tag }}<!-- {{ field.name }} --></td>
                        <td>{{ field }}</td></tr>
                    {% endfor %}
                {% else %}
                    {% for field in form %}
                        <tr><td>{{ field }}</td></tr>
                    {% endfor %}
                {% endif %}
                </table></td>
            {% endfor %}
         </tr></table>
             <input class="btn btn-primary" type="submit" value="Save" />

     </form>

    <script>

    $(document).ready(function(){
        $(".RETAIL_90_MAIL_RATES_B_FIELD").hide($("#id_RETAIL_90_MAIL_RATES_B").val().substring(0,1) != "Y");
        $(".RETAIL_90_MAIL_RATES_G_FIELD").hide($("#id_RETAIL_90_MAIL_RATES_B").val().substring(0,1) != "Y");

        $("#id_RETAIL_90_MAIL_RATES_B").change(function(){
            $(".RETAIL_90_MAIL_RATES_B_FIELD").toggle($("#id_RETAIL_90_MAIL_RATES_B").val() != "N");
            });

        $("#id_RETAIL_90_MAIL_RATES_G").change(function(){
            $(".RETAIL_90_MAIL_RATES_G_FIELD").toggle($("#id_RETAIL_90_MAIL_RATES_G").val() != "N");
            });
    });

    $('cfd_form :input').change(function(){
        alert("Form changed");
    });

    </script>

 {% endblock %}

cfd/templates/cfd_recover_form.html
<!--Template for the confirmation screen when reverting to a historical version of a record-->
<!-- This line specifies that the content here should be merged into the base.html-->
{% extends 'base.html' %}
{% load i18n static %}
{% load filters %}
{% load static %}

{% block main %}
    

<form  method="post" id="cfd_form">{% csrf_token %}

    <div class="col">
        {% include "snippets/form_snippet.html" with form=form fieldsets=fieldsets %}
    </div>

    <button type="button" class="btn btn-primary cfd-btn" data-toggle="modal" data-target="#myModal">
        Save
    </button>
        
    <div class="modal" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">
                    
            <div class="modal-header">
                <h4 class="modal-title">Confirm Form Submission</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
        
            <div class="modal-body">
                Are you sure you want to revert this object to this version ?
            </div>
        
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                <input id="submit" class="btn btn-primary" type="submit" value="Save" />
            </div>
        
            </div>
        </div>
    </div>       
</form>

{% endblock %}


{% block scripts %}

<script src="{% static '/admin/js/vendor/jquery/jquery.js' %}"></script>
<script src="{% static '/admin/js/jquery.init.js' %}"></script>
<script src="{% static '/admin/js/core.js' %}"></script>
<script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
<script src="{% static '/js/collapse.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="{% static '/js/forms.js' %}"></script>

{% endblock %}